#! /usr/bin/env node
import inquirer from "inquirer";
// 1 step: random number will be generated by the computer
// 2 step: user input for guessing number
// 3 step: comparison of user input and computer generated number
// simple game 
// const randomnumber = 15;
// const answer = await inquirer.prompt([{
//     name: "userguessednumber",
//     type: "number",
//     message: "Please Guess a Number:"
// },
// ])
// if (answer.userguessednumber === randomnumber){
//     console.log("You won!");
// } else {
//     console.log("You lost");
// }
// modified game with automation generation of randum number
// const randomnumber = Math.random();
// console.log(randomnumber);
// this is not a good one due to output given is 0.3209856067483454.
// updated game version with automation of generated numbers
const randomnumber = Math.floor(Math.random() * 10 + 1);
const answer = await inquirer.prompt([{
        name: "userguessednumber",
        type: "number",
        message: "Please Guess a Number between 1 to 10:"
    },
]);
console.log(answer);
if (answer.userguessednumber === randomnumber) {
    console.log("You won!");
}
else {
    console.log("You lost");
}
